"""
agentadmit.cli
--------------
CLI tool for AgentAdmit SDK setup.

Usage:
    agentadmit init          # Generate config file and keys
    agentadmit keys          # Generate/regenerate RS256 key pair
    agentadmit check         # Validate configuration
"""

import argparse
import os
import sys
from pathlib import Path


SAMPLE_CONFIG = '''# AgentAdmit Configuration
# Generated by: agentadmit init
# Docs: https://docs.agentadmit.app/sdk

# Your app identity (get these from your AgentAdmit dashboard at app.agentadmit.app)
app_name: "My App"
app_id: ""                    # From your AgentAdmit dashboard
api_key: ""                   # From your AgentAdmit dashboard (aa_live_xxxx)
api_base_url: "http://localhost:8000"  # Your app's base URL

# AgentAdmit hosted service URLs (do not change unless instructed)
agentadmit_api_url: "https://api.agentadmit.app"
agentadmit_verify_url: "https://api.agentadmit.io/v1/verify"

# Route prefix for AgentAdmit endpoints on your app
route_prefix: "/agentadmit"

# User lookup — the field in your users table/collection that stores the user ID
user_lookup_field: "user_id"  # Change to "id", "_id", "uid", etc. as needed

# Define your scopes — what can agents access in your app?
# Each scope needs: name, description, category, role
# These MUST match the scopes you registered on your AgentAdmit dashboard.
scopes:
  # Example: User-facing scopes
  # - name: "read:orders"
  #   description: "View order history and delivery status"
  #   category: "Shopping"
  #   role: "user"
  #
  # - name: "create:orders"
  #   description: "Place new orders"
  #   category: "Shopping"
  #   role: "user"
  #
  # Example: Admin/Owner scopes
  # - name: "read:analytics"
  #   description: "View platform analytics and user metrics"
  #   category: "Admin"
  #   role: "admin"

# Connection duration options shown to users
durations:
  - label: "1 Hour"
    seconds: 3600
  - label: "24 Hours"
    seconds: 86400
  - label: "7 Days"
    seconds: 604800
  - label: "30 Days"
    seconds: 2592000
  - label: "Until I Revoke"
    seconds: null              # No expiry — user revokes manually

# Local storage (for your app's user lookups only — AgentAdmit handles token/connection storage)
storage:
  backend: "mongodb"           # "mongodb" or "memory" (for testing)
  uri: "mongodb://localhost:27017"
  database: "your_database"    # Your app's database
'''


def cmd_init(args):
    """Generate config file and keys."""
    config_path = Path("agentadmit.yaml")

    if config_path.exists() and not args.force:
        print(f"Config file already exists: {config_path}")
        print("Use --force to overwrite.")
        return

    # Write config
    config_path.write_text(SAMPLE_CONFIG)
    print(f"Created: {config_path}")

    print()
    print("Next steps:")
    print("  1. Sign up at app.agentadmit.app and get your app_id + api_key")
    print("  2. Edit agentadmit.yaml — add your credentials and define your scopes")
    print("  3. Add AgentAdmitMiddleware to your app")
    print("  4. Add @require_scope_if_agent('your:scope') to protected routes")
    print()
    print("See: https://docs.agentadmit.app/sdk/quickstart")


def cmd_keys(args):
    """Generate or regenerate RS256 key pair."""
    from agentadmit.keys import generate_key_pair
    output = args.output or "keys"
    priv, pub = generate_key_pair(output)
    print(f"Generated: {priv}")
    print(f"Generated: {pub}")


def cmd_check(args):
    """Validate configuration."""
    config_path = args.config or "agentadmit.yaml"
    try:
        from agentadmit.config import load_config
        config = load_config(config_path)
        print(f"Config: {config_path}")
        print(f"App: {config.app_name}")
        print(f"Scopes: {len(config.scopes)}")
        print(f"Tiers: {len(config.tiers)}")
        print(f"Durations: {len(config.durations)}")
        print(f"Storage: {config.storage.backend}")

        # Check keys
        from agentadmit.keys import load_private_key, load_public_key
        try:
            load_private_key(config.private_key_path)
            load_public_key(config.public_key_path)
            print("Keys: OK")
        except Exception as e:
            print(f"Keys: MISSING ({e})")

        if len(config.scopes) == 0:
            print()
            print("WARNING: No scopes defined. Edit agentadmit.yaml to add scopes.")
        else:
            print()
            print("Scopes:")
            for s in config.scopes:
                print(f"  {s.name} — {s.description} [{s.category}/{s.role}]")

        print()
        print("Configuration is valid.")

    except Exception as e:
        print(f"Configuration error: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        prog="agentadmit",
        description="AgentAdmit SDK — User-mediated AI agent authorization",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Generate config file and keys")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config")

    # keys
    keys_parser = subparsers.add_parser("keys", help="Generate RS256 key pair")
    keys_parser.add_argument("--output", "-o", help="Output directory (default: keys/)")

    # check
    check_parser = subparsers.add_parser("check", help="Validate configuration")
    check_parser.add_argument("--config", "-c", help="Config file path (default: agentadmit.yaml)")

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "keys":
        cmd_keys(args)
    elif args.command == "check":
        cmd_check(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
