"""
agentadmit.cli
--------------
CLI tool for AgentAdmit SDK setup.

Usage:
    agentadmit init          # Generate config file and keys
    agentadmit keys          # Generate/regenerate RS256 key pair
    agentadmit check         # Validate configuration
"""

import argparse
import os
import sys
from pathlib import Path


SAMPLE_CONFIG = '''# AgentAdmit Configuration
# Generated by: agentadmit init
# Docs: https://agentadmit.com/docs

# Your app identity (get these from your AgentAdmit dashboard at agentadmit.com)
app_name: "My App"
app_id: ""                    # From your AgentAdmit dashboard
api_key: ""                   # aa_test_xxxx for development, aa_live_xxxx for production
                              # Both route through AgentAdmit — no local-only mode
                              # Test keys: relaxed rate limits, no billing, test data separate
                              # Live keys: full billing, real introspection, marketplace seeding
api_base_url: "http://localhost:8000"  # Your app's base URL

# AgentAdmit hosted service URLs (do not change unless instructed)
agentadmit_api_url: "https://api.agentadmit.com"
agentadmit_verify_url: "https://api.agentadmit.com/api/v1/verify"

# Route prefix for AgentAdmit endpoints on your app
route_prefix: "/agentadmit"

# User lookup — the field in your users table/collection that stores the user ID
user_lookup_field: "user_id"  # Change to "id", "_id", "uid", etc. as needed

# Define your scopes — what can agents access in your app?
# Each scope needs: name, description, category, role
# These MUST match the scopes you registered on your AgentAdmit dashboard.
scopes:
  # Example: User-facing scopes
  # - name: "read:orders"
  #   description: "View order history and delivery status"
  #   category: "Shopping"
  #   role: "user"
  #
  # - name: "create:orders"
  #   description: "Place new orders"
  #   category: "Shopping"
  #   role: "user"
  #
  # Example: Admin/Owner scopes
  # - name: "read:analytics"
  #   description: "View platform analytics and user metrics"
  #   category: "Admin"
  #   role: "admin"

# Connection duration options shown to users
durations:
  - label: "1 Hour"
    seconds: 3600
  - label: "24 Hours"
    seconds: 86400
  - label: "7 Days"
    seconds: 604800
  - label: "30 Days"
    seconds: 2592000
  - label: "Until I Revoke"
    seconds: null              # No expiry — user revokes manually

# Local storage (for your app's user lookups only — AgentAdmit handles token/connection storage)
storage:
  backend: "mongodb"           # "mongodb" or "memory" (for testing)
  uri: "mongodb://localhost:27017"
  database: "your_database"    # Your app's database
'''


def cmd_init(args):
    """Generate config file and keys."""
    config_path = Path("agentadmit.yaml")

    if config_path.exists() and not args.force:
        print(f"Config file already exists: {config_path}")
        print("Use --force to overwrite.")
        return

    # Write config
    config_path.write_text(SAMPLE_CONFIG)
    print(f"Created: {config_path}")

    print()
    print("Next steps:")
    print("  1. Sign up at agentadmit.com and get your app_id + api_key")
    print("  2. Edit agentadmit.yaml — add your credentials and define your scopes")
    print("  3. Add AgentAdmitMiddleware to your app")
    print("  4. Add @require_scope_if_agent('your:scope') to protected routes")
    print()
    print("See: https://agentadmit.com/docs/app-owner-guide")


def cmd_keys(args):
    """DEPRECATED — AgentAdmit is a hosted service. Local keys are not needed."""
    print("AgentAdmit is a hosted service. All token signing is handled by api.agentadmit.com.")
    print("Local RSA keys are not needed. Remove private_key_path and public_key_path from agentadmit.yaml.")
    print()
    print("If you previously generated keys, they can be safely deleted.")


def cmd_check(args):
    """Validate configuration."""
    config_path = args.config or "agentadmit.yaml"
    try:
        from agentadmit.config import load_config
        config = load_config(config_path)
        print(f"Config: {config_path}")
        print(f"App: {config.app_name}")
        print(f"Scopes: {len(config.scopes)}")
        print(f"Tiers: {len(config.tiers)}")
        print(f"Durations: {len(config.durations)}")
        print(f"Storage: {config.storage.backend}")

        # Hosted service check
        if config.api_key:
            print(f"API Key: configured ({config.api_key[:12]}...)")
        else:
            print("API Key: NOT SET — get one from your AgentAdmit dashboard")
        if config.agentadmit_verify_url:
            print(f"Verify URL: {config.agentadmit_verify_url}")
        else:
            print("Verify URL: NOT SET — defaults to https://api.agentadmit.com/api/v1/verify")

        if len(config.scopes) == 0:
            print()
            print("WARNING: No scopes defined. Edit agentadmit.yaml to add scopes.")
        else:
            print()
            print("Scopes:")
            for s in config.scopes:
                print(f"  {s.name} — {s.description} [{s.category}/{s.role}]")

        print()
        print("Configuration is valid.")

    except Exception as e:
        print(f"Configuration error: {e}")
        sys.exit(1)


def cmd_sync(args):
    """Sync scopes from agentadmit.yaml to the AgentAdmit hosted service."""
    config_path = args.config or "agentadmit.yaml"
    try:
        from agentadmit.config import load_config
        config = load_config(config_path)
        print(f"Config: {config_path}")
        print(f"App: {config.app_name} ({config.app_id})")
        print(f"Scopes: {len(config.scopes)}")
        print(f"Service: {config.agentadmit_api_url}")
        print()

        if not config.app_id or not config.api_key:
            print("ERROR: app_id and api_key must be set in agentadmit.yaml.")
            print("Get these from your AgentAdmit dashboard at agentadmit.com.")
            sys.exit(1)

        if not config.scopes:
            print("WARNING: No scopes defined. Add scopes to agentadmit.yaml first.")
            sys.exit(1)

        from agentadmit.middleware import _sync_scopes_to_hosted_service
        print(f"Syncing {len(config.scopes)} scopes to {config.agentadmit_api_url}...")
        success = _sync_scopes_to_hosted_service(config)

        if success:
            print()
            print(f"✅ {len(config.scopes)} scopes synced successfully.")
            print("View them in your AgentAdmit dashboard under Apps → Scopes.")
        else:
            print()
            print("❌ Sync failed. Check the error messages above.")
            print("Make sure the AgentAdmit hosted service is reachable and your API key is valid.")
            sys.exit(1)

    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        prog="agentadmit",
        description="AgentAdmit SDK — User-mediated AI agent authorization",
    )
    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Generate config file and keys")
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing config")

    # keys
    keys_parser = subparsers.add_parser("keys", help="Generate RS256 key pair")
    keys_parser.add_argument("--output", "-o", help="Output directory (default: keys/)")

    # check
    check_parser = subparsers.add_parser("check", help="Validate configuration")
    check_parser.add_argument("--config", "-c", help="Config file path (default: agentadmit.yaml)")

    # sync
    sync_parser = subparsers.add_parser("sync", help="Sync scopes from agentadmit.yaml to the hosted service")
    sync_parser.add_argument("--config", "-c", help="Config file path (default: agentadmit.yaml)")

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "keys":
        cmd_keys(args)
    elif args.command == "check":
        cmd_check(args)
    elif args.command == "sync":
        cmd_sync(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
